### ISSUE TITLE
terminate called after throwing an instance of 'LibError'

### ISSUE THREAD

**Issue by kbarlee** [aligungr/UERANSIM#258]
Hey Ali

First off, congrats! This is an awesome piece of software!

I have just fired it up on a 20.04 VM and connected it to my Open5GS cloud cluster, and it seems to work really well.

When I launch the `nr-gnb` and `nr-ue`, all seems to work fine for a wee while. I need to manually add a route, eg 
```
sudo ip route add 10.45.0.0/16 dev uesimtun0
```
before being able to generate traffic (eg downloading a file hosted on the UPF server). Getting some decent throughput rates of up to 270Mbps; not sure if this is capped by the VPN software I'm running as that will surely be a bottleneck, also the $40 VMs for UERANSIM and the Open5GS-UPF might not have enough oomf. Do you have a headline figure in mind that you would expect to see?

When running for a few mins, `nr-gnb` repeatedly seems to crash. Are you able to make sense of this error?
```
$ sudo UERANSIM/build/nr-gnb -c UERANSIM/config/open5gs-gnb.yaml
UERANSIM v3.1.0
[2021-02-17 13:54:18.975] [sctp] [info] Trying to establish SCTP connection... (10.10.0.5:38412)
[2021-02-17 13:54:19.002] [sctp] [info] SCTP connection established (10.10.0.5:38412)
[2021-02-17 13:54:19.002] [sctp] [debug] SCTP association setup ascId[9]
[2021-02-17 13:54:19.002] [ngap] [debug] Sending NG Setup Request
[2021-02-17 13:54:19.011] [ngap] [debug] NG Setup Response received
[2021-02-17 13:54:19.011] [ngap] [info] NG Setup procedure is successful
[2021-02-17 13:54:24.516] [mr] [info] New UE connected to gNB. Total number of UEs is now: 1
[2021-02-17 13:54:24.517] [rrc] [debug] Sending RRC Setup for UE[3]
[2021-02-17 13:54:24.517] [ngap] [debug] Initial NAS message received from UE 3
[2021-02-17 13:54:24.546] [ngap] [debug] Initial Context Setup Request received
[2021-02-17 13:54:24.766] [ngap] [info] PDU session resource is established for UE[3] count[1]
terminate called after throwing an instance of 'LibError'
  what():  sendto failed:  Resource temporarily unavailable
Aborted
```
```
$ sudo UERANSIM/build/nr-ue -c UERANSIM/config/open5gs-ue-235047364000121.yaml
UERANSIM v3.1.0
[2021-02-17 13:54:24.516] [nas] [debug] NAS layer started
[2021-02-17 13:54:24.516] [rrc] [debug] RRC layer started
[2021-02-17 13:54:24.516] [nas] [info] UE switches to state: MM-DEREGISTERED/PLMN-SEARCH
[2021-02-17 13:54:24.516] [nas] [info] UE connected to gNB
[2021-02-17 13:54:24.516] [nas] [info] UE switches to state: MM-DEREGISTERED/NORMAL-SERVICE
[2021-02-17 13:54:24.516] [nas] [info] UE switches to state: MM-REGISTERED-INITIATED/NA
[2021-02-17 13:54:24.517] [rrc] [debug] Sending RRC Setup Request
[2021-02-17 13:54:24.517] [rrc] [info] RRC connection established
[2021-02-17 13:54:24.517] [nas] [info] UE switches to state: CM-CONNECTED
[2021-02-17 13:54:24.533] [nas] [debug] Received rand[6AC1B3CE610DD2A071C2492CBE52F9DC] autn[2DF123B2474F9001C4AA856DFDF3649E]
[2021-02-17 13:54:24.533] [nas] [debug] Calculated res[648CA7F47EAC111C] ck[A55B10C9180DEAFFD4C14BB9E1BBFD3B] ik[6F0D88DB08A89977CA6FBD2E367F57CD] ak[2DF123B23511] mac_a[C4AA856DFDF3649E]
[2021-02-17 13:54:24.533] [nas] [debug] Used snn[5G:mnc004.mcc235.3gppnetwork.org] sqn[00000000725E]
[2021-02-17 13:54:24.533] [nas] [debug] Derived kSeaf[1D8DD7084DA38C42D26E7C2B9DAE3CE88C2D450969AD34A451001DB6F58BDFF0] kAusf[4BC2146BF23F97682ADBF4CCD80886DD7A902ABFAAB999984DF399C3429D44A5] kAmf[78C94299348F1C968F65A28F873B185FB50D87003975A80FB5E29A9F3A6E037E]
[2021-02-17 13:54:24.538] [nas] [debug] Derived kNasEnc[5309B1E56398CE592F6629DC803DEB0B] kNasInt[F2DD4B38F2A769C141FB9F1AFB9D2E04]
[2021-02-17 13:54:24.538] [nas] [debug] Selected integrity[1] ciphering[0]
[2021-02-17 13:54:24.546] [nas] [debug] T3512 started with int[32400]
[2021-02-17 13:54:24.546] [nas] [info] UE switches to state: MM-REGISTERED/NORMAL-SERVICE
[2021-02-17 13:54:24.546] [nas] [info] Initial Registration is successful
[2021-02-17 13:54:24.546] [nas] [info] Initial PDU sessions are establishing [1#]
[2021-02-17 13:54:24.546] [nas] [debug] Sending PDU session establishment request
[2021-02-17 13:54:24.766] [nas] [info] PDU Session establishment is successful PSI[1]
[2021-02-17 13:54:24.783] [app] [info] Connection setup for PDU session[1] is successful, TUN interface[uesimtun0, 10.45.0.47] is up.
[2021-02-17 13:56:57.050] [mr] [warning] UE disconnected from gNB, RLS released [RLS_HEARTBEAT_TIMEOUT]
[2021-02-17 13:57:01.352] [rls] [warning] RLS uplink delivery request without connection
[2021-02-17 13:57:01.353] [rls] [warning] RLS uplink delivery request without connection
[2021-02-17 13:57:01.353] [rls] [warning] RLS uplink delivery request without connection
....
```
After this I need to restart both  `nr-gnb` and `nr-ue`

Cheers
Kenny

**Comment by aligungr** [comment]
Hi Kenny

There is a very high possibility that the bottleneck is caused by the external environment ie. outside of UERANSIM. Such as Linux kernel, your CPU, network adapter or VPN software etc. Indeed, that error is highly related to this issue. `sendto failed:  Resource temporarily unavailable` means that the previous packet didn't fully leave the kernel and next packet derived while there's another packet pending.

Actually gNB should not crash in that case, it should just ignore the error and drop the packet. Thanks for reporting this issue. I'll fix this (this won't increase your bandwidth but at least the crash will be gone.)

Thank you

**Comment by s5uishida** [comment]
Hi @kbarlee and @aligungr 

As an aside, I'm using a low latency kernel, like UE / RAN in OpenAirInterface. 

Of course, changing the kernel with the same HW does not result in low latency. However, it reduces the fluctuation (jitter?) of the delay and makes the delay almost constant.  

- Host OS - Ubuntu 20.04 `5.4.0-65-lowlatency #73-Ubuntu SMP PREEMPT`
- Guest OSs - Ubuntu 20.04 `5.4.0-65-lowlatency #73-Ubuntu SMP PREEMPT`

For example, could you think there is any effect in such an environment?

**Comment by aligungr** [comment]
@s5uishida

Linux low latency option may reduce the **ping**, but the overall **throughput** will be the same (or even lower than the first case). `lowlatency` option may be useful for -for example- receiving from radio antennas close to real-time. But for normal IP packet delivery, `lowlatency` option won't effect the bandwidth.

We can *normally* say that the most of the time is occupied by either kernel or IO device, but still there are many optimization opportunities of course in both UE/gNB and core network side, (and we're open for such an investigation :)

**Comment by j13tw** [comment]
Hello @aligungr 
I also face on this problem
I try UERANSIM version v3.0.2 and v3.1.0 dual release version
the test environment is on bare metal & docker container (with kubernetes)
All of OS is ubuntu 20.04, and use the HP DL360 Server Board (with dual E5-2620/ RAM 48G)
Most of my gnb service unusual exit is on my test iperf3 with high throughput (1Gbps)
and I use iperf3 with low throughput (100Mbps) or ping external network the gnb/ue are work well
i guess the gnb crash is result in the socket with buffer full or socket's fd_setsize for select count more than 1023,
and the gnb service can't process or get the packet.

Perhaps this report can help you fix this issue

**Comment by aligungr** [comment]
Hello @j13tw 

I've just pushed some (possible) fix to the master. Please try again with high throughput if you could. By the way, I wonder if you encounter the exact same error with Kenny, or a similar one?

**Comment by j13tw** [comment]
Hello @aligungr 
I try the newest master branch and compare with release v3.1.0
I used the kubernetes VIM and open5gs v2.1.7 to check the gnb/ue running status
in v3.1.0 the gnb/ue are possible crash (like figure)
and the newest master branch testing are not crash
here is my test iperf3 command  
```iperf3 -c <server-ip> -B <ue-ip> -u -b 1G -t 600```

gnb fail figure
![截圖 2021-02-28 上午2 21 42](https://user-images.githubusercontent.com/27864573/109397616-87697480-7972-11eb-8888-35c67183b53d.png)

ue fail figure
![截圖 2021-02-28 上午2 21 59](https://user-images.githubusercontent.com/27864573/109397618-89333800-7972-11eb-815b-26fd0e7b441f.png)

**Comment by kbarlee** [comment]
Hey @aligungr 

Finally got round to testing again - the crash issue is fixed, so closing this issue. Thanks!

Kenny

**Comment by Altaf123** [comment]
I am using ubuntu 22.04 host for open5gs and 22.04 VM for UERANSIM. With V3.2.6 I am still getting the error as LibError. Is there a way to resolve this.
