### ISSUE TITLE
ueransim integration with OAI 5G Core

### ISSUE THREAD

**Issue by infinitydon** [aligungr/UERANSIM#284]
Hi,

I am currently trying to use ueransim with Open Air Interface 5G core but the AMF keeps crashing, I have opened a case with the OAI team and below is the response I got.

**_By regarding the pcap, it seems to me that the Initial UE Message was not encoded correctly. More specifically, "Assigned Criticality" of User Location Information IE should be "reject" instead of "ignore" (please refer to 3GPP TS 38.413 V16.0.0 (2019-12), section 9.2.5.1 for more information).  As a result, AMF crashes since it couldn't handle the next message.
Could you please verify UERANSIM so that it can generate the Initial UE Message correctly._**

Attached is some of the logs and pcap traces.

[oai-ueransim-logs-pcap.zip](https://github.com/aligungr/UERANSIM/files/6264055/oai-ueransim-logs-pcap.zip)

**Comment by aligungr** [comment]
Hi Adigun, thanks for reporting the issue, I'll fix this in a few days.

**Comment by aligungr** [comment]
Hello again Adigun

I had a time to look at this issue, and I've just fixed and pushed to the master. It should work now.

Thanks

**Comment by infinitydon** [comment]
Thanks Ali..

I just tried it now but still not working, I have sent the latest pcap (the criticality value is now set to reject as they advised) to the OAI support team to check it further.

**Comment by infinitydon** [comment]
So there is some sort of progress but Authentication is failing, I know this might be the issue of setting OP,OPC, security Key etc but I have confirmed the configuration.

```
UERANSIM v3.1.6
[2021-04-16 10:25:34.566] [nas] [debug] NAS layer started
[2021-04-16 10:25:34.566] [rrc] [debug] RRC layer started
[2021-04-16 10:25:34.567] [nas] [info] UE switches to state [MM-DEREGISTERED/PLMN-SEARCH]
[2021-04-16 10:25:34.568] [nas] [info] UE connected to gNB
[2021-04-16 10:25:34.568] [nas] [info] UE switches to state [MM-DEREGISTERED/NORMAL-SERVICE]
[2021-04-16 10:25:34.568] [nas] [debug] Sending Initial Registration
[2021-04-16 10:25:34.569] [nas] [info] UE switches to state [MM-REGISTER-INITIATED/NA]
[2021-04-16 10:25:34.569] [rrc] [debug] Sending RRC Setup Request
[2021-04-16 10:25:34.571] [rrc] [info] RRC connection established
[2021-04-16 10:25:34.573] [nas] [info] UE switches to state [CM-CONNECTED]
[2021-04-16 10:25:34.616] [nas] [error] AUTN validation MAC mismatch. expected: E62553BE8EC171B4 received: A8345F017730B980
[2021-04-16 10:25:49.581] [nas] [debug] NAS timer[3510] expired [1]
[2021-04-16 10:25:49.581] [nas] [info] UE switches to state [MM-DEREGISTERED/NA]
[2021-04-16 10:25:49.582] [nas] [info] UE switches to state [5U2-NOT-UPDATED]
[2021-04-16 10:25:49.582] [nas] [info] Performing local release of NAS connection
```

Attached is the pcap also, maybe you might have some insight.

[oai-amf-ueransim-april-16.zip](https://github.com/aligungr/UERANSIM/files/6325234/oai-amf-ueransim-april-16.zip)

I have informed OAI dev also to check.

**Comment by aligungr** [comment]
If you are absolutely sure about the configuration parameters, then I suspect there is a potential bug in either UERANSIM or OAI side. And I think authentication procedure should work fine in UERANSIM side, as the authentication procedure was intensely tested with at least 4 different core networks. Let's await OAI team, perhaps they could find anything on OAI side.

**Comment by jssidhu94** [comment]
Hi,

Any update on this issue? because I am also trying the same thing and facing the same issue:

on UE:

UERANSIM v3.1.7
[2021-04-28 15:53:14.391] [nas] [info] UE switches to state [MM-DEREGISTERED/PLMN-SEARCH]
[2021-04-28 15:53:14.392] [rls] [debug] Coverage change detected. [1] cell entered, [0] cell exited
[2021-04-28 15:53:14.392] [nas] [info] Serving cell determined [UERANSIM-gnb-208-95-1]
[2021-04-28 15:53:14.392] [nas] [info] UE switches to state [MM-DEREGISTERED/NORMAL-SERVICE]
[2021-04-28 15:53:14.392] [nas] [debug] Sending Initial Registration
[2021-04-28 15:53:14.393] [nas] [info] UE switches to state [MM-REGISTER-INITIATED/NA]
[2021-04-28 15:53:14.393] [rrc] [debug] Sending RRC Setup Request
[2021-04-28 15:53:14.393] [rrc] [info] RRC connection established
[2021-04-28 15:53:14.394] [nas] [info] UE switches to state [CM-CONNECTED]
[2021-04-28 15:53:29.404] [nas] [debug] NAS timer[3510] expired [1]
[2021-04-28 15:53:29.404] [nas] [info] UE switches to state [MM-DEREGISTERED/NA]
[2021-04-28 15:53:29.404] [nas] [info] UE switches to state [5U2-NOT-UPDATED]
[2021-04-28 15:53:29.404] [nas] [info] Performing local release of NAS connection
[2021-04-28 15:53:29.404] [nas] [info] UE switches to state [MM-DEREGISTERED/ATTEMPTING-REGISTRATION]
[2021-04-28 15:53:29.404] [nas] [info] UE switches to state [CM-IDLE]


on gNB:

UERANSIM v3.1.7
[2021-04-28 15:51:15.602] [sctp] [info] Trying to establish SCTP connection... (192.168.70.132:38412)
[2021-04-28 15:51:15.606] [sctp] [info] SCTP connection established (192.168.70.132:38412)
[2021-04-28 15:51:15.606] [sctp] [debug] SCTP association setup ascId[7]
[2021-04-28 15:51:15.606] [ngap] [debug] Sending NG Setup Request
[2021-04-28 15:51:15.625] [ngap] [debug] NG Setup Response received
[2021-04-28 15:51:15.625] [ngap] [info] NG Setup procedure is successful
[2021-04-28 15:53:14.389] [rls] [debug] New UE signal detected, total [1] UEs in coverage
[2021-04-28 15:53:14.393] [rrc] [info] RRC Setup for UE[1]
[2021-04-28 15:53:14.394] [ngap] [debug] Initial NAS message received from UE[1]
[2021-04-28 15:53:30.403] [rls] [debug] New UE signal detected, total [2] UEs in coverage
[2021-04-28 15:53:31.672] [rls] [debug] Signal lost detected for UE[1]
[2021-04-28 15:53:31.672] [ngap] [debug] Sending UE Context release request (NG-RAN node initiated)
[2021-04-28 15:53:31.819] [sctp] [debug] SCTP association shutdown (clientId: 2)
[2021-04-28 15:53:31.819] [sctp] [warning] Unhandled SCTP notification received
[2021-04-28 15:53:31.819] [ngap] [error] Association terminated for AMF[2]
[2021-04-28 15:53:31.819] [ngap] [debug] Removing AMF context[2]

**Comment by infinitydon** [comment]
@jssidhu94 - There is an open issue in the [OAI 5g mailing list](https://lists.eurecom.fr/sympa/arc/openair5g-user/2021-04/msg00010.html), seems the issue is with OAI code.

**Comment by infinitydon** [comment]
@jssidhu94 - The AMF issue has been fixed, UE attach is now successful but the following oai branches should be used:

AMF - **_quectel_**
SMF - **_develop_**

Remaining issue now is the ping test from UE to UPF which is currently failing, issue seems on the UPF side because ping request is getting to the UPF side but response is not been sent back.

**Comment by infinitydon** [comment]
@aligungr - I did another test, ping test works when destination is not the UPF interface, so for example ping test to 4.2.2.2 works.

I will proceed to close this, at least we have confirmed that ueransim works with OAI stack. Thanks for the support.

**Comment by aligungr** [comment]
Thanks for the information @infinitydon

**Comment by auandrew** [comment]
Please note that I've been also similarly trying to use UERANSIM to test oai-cn5g, but recently run into a new authen failure on the UE side.  It's reported in issue #320.

**Comment by aligungr** [comment]
@infinitydon

I wonder what version of UERANSIM did you used while successfully testing OAI core network. Because some of the users encounters SQN error. And SQN failure controls were added in v3.1.8. Did you use the version before v3.1.8 or after?

**Comment by infinitydon** [comment]
Hi @aligungr - When I started initially I used v3.1.6 but it eventually worked with v3.1.8 (I did not choose this version specifically, I only decided to upgrade ueransim to the latest version as at the time I tested).

For reference purpose below is the AMF config that worked in my own case:

```
    {
      INSTANCE_ID = 0;            # 0 is the default
      PID_DIRECTORY = "/var/run";   # /var/run is the default

      AMF_NAME = "OAI-AMF";

      RELATIVE_CAPACITY = 30;
      # Display statistics about whole system (in seconds)
      STATISTICS_TIMER_INTERVAL = 20;  # YOUR CONFIG HERE

      CORE_CONFIGURATION:
      {
        EMERGENCY_SUPPORT = "false";
      };

      GUAMI:
      {
        MCC = "208"; MNC = "95"; RegionID = "128"; AMFSetID = "1"; AMFPointer = "1" # YOUR GUAMI CONFIG HERE
      }

      SERVED_GUAMI_LIST = (
        {MCC = "208"; MNC = "95"; RegionID = "128"; AMFSetID = "1"; AMFPointer = "0"}, #48bits <MCC><MNC><RegionID><AMFSetID><AMFPointer>
        {MCC = "460"; MNC = "11"; RegionID = "10"; AMFSetID = "1"; AMFPointer = "1"}  #48bits <MCC><MNC><RegionID><AMFSetID><AMFPointer>
      );

      PLMN_SUPPORT_LIST = (
      {
        MCC = "208"; MNC = "95"; TAC = 0xa000;  # YOUR PLMN CONFIG HERE
        SLICE_SUPPORT_LIST = (
          {SST = "222"; SD = "123"},  # YOUR NSSAI CONFIG HERE
          {SST = "1"; SD = "1"}   # YOUR NSSAI CONFIG HERE
         )
      }
      );

      INTERFACES:
      {
        # AMF binded interface for N1/N2 interface (NGAP)
        NGAP_AMF:
        {
          INTERFACE_NAME = "eth0";  # YOUR NETWORK CONFIG HERE
          IPV4_ADDRESS   = "read";
          PORT           = 38412;                            # YOUR NETWORK CONFIG HERE
          PPID           = 60;                               # YOUR NETWORK CONFIG HERE
        };

        # AMF binded interface for SBI (N11 (SMF)/N12 (AUSF), etc.)
        N11:
        {
          INTERFACE_NAME = "eth0"; # YOUR NETWORK CONFIG HERE
          IPV4_ADDRESS   = "read";
          PORT           = 80;                             # YOUR NETWORK CONFIG HERE
          API_VERSION    = "v1";            # YOUR AMF API VERSION CONFIG HERE


          SMF_INSTANCES_POOL = (
            {SMF_INSTANCE_ID = 1; IPV4_ADDRESS = "0.0.0.0"; PORT = "80"; VERSION = "v1"; SELECTED = "true"},   # YOUR SMF CONFIG HERE
            {SMF_INSTANCE_ID = 2; IPV4_ADDRESS = "0.0.0.0"; PORT = "80"; VERSION = "v1"; SELECTED = "false"} # YOUR SMF CONFIG HERE
          );
        };

        NRF :
        {
          IPV4_ADDRESS = "10.233.99.8"; # YOUR NRF CONFIG HERE
          PORT         =  80;  # YOUR NRF CONFIG HERE (default: 80)
          API_VERSION  =  "v1"; # YOUR NRF API VERSION FOR SBI CONFIG HERE
        };

        AUSF :
        {
          IPV4_ADDRESS = "127.0.0.1"; # YOUR AUSF CONFIG HERE
          PORT         = 80;   # YOUR AUSF CONFIG HERE (default: 80)
          API_VERSION  = "v1"; # YOUR AUSF API VERSION FOR SBI CONFIG HERE
        };

      };

      SUPPORT_FEATURES:
      {
         # STRING, {"yes", "no"},
         NF_REGISTRATION = "no";  # Set to yes if AMF resgisters to an NRF
         SMF_SELECTION   = "yes";  # Set to yes to enable SMF discovery and selection
         EXTERNAL_AUSF   = "no";  # Set to yes if AMF works with an external AUSF
         EXTERNAL_UDM    = "no";  # Set to yes if AMF works with an external UDM
      }

      AUTHENTICATION:
      {
        ## MySQL mandatory options
        MYSQL_server = "10.233.51.156"; # MySQL Server address
        MYSQL_user   = "root";   # Database server login
        MYSQL_pass   = "xdexxxx";   # Database server password
        MYSQL_db     = "oai_db";     # Your database name

        ## OP
        OPERATOR_key = "63bfa50ee6523365ff14c1f45f88737d"; # OP key matching your database
        RANDOM = "true";
      };

      NAS:
      {
        ORDERED_SUPPORTED_INTEGRITY_ALGORITHM_LIST = [ "NIA1" , "NIA2" ];
        ORDERED_SUPPORTED_CIPHERING_ALGORITHM_LIST = [ "NEA1" , "NEA2" ];
      };

    };


    MODULES =
    {
      NGAP_MESSAGE = (
        {MSG_NAME = "NGSetupRequest"; ProcedureCode = 21; TypeOfMessage = "initialMessage"}
      );
    };
```

**Comment by infinitydon** [comment]
@tian008123 - I did not include the config file in the docker image, I mounted it as a confimap (I am using k8s), I suppose this should also work using docker-compose.

I did not use any file to change the AMF config, the above config I shared is what I used.

**Comment by infinitydon** [comment]
@tian008123 

The OAI AMF code as I understand currently does not support setting the NIA0 and NEA0 using environment variables, you will need to invoke the amf command with the config file instead of using the environment variables.

You can try to change your AMF section to something like this:

```
    oai-amf:
        container_name: "oai-amf"
        image: oai-amf:develop
        command: /openair-amf/bin/oai_amf -c /openair-amf/etc/amf.conf -o
        depends_on:
            - mysql
        volumes:
            - ./amf-healthcheck.sh:/openair-amf/bin/amf-healthcheck.sh
            - ./amf.conf:/openair-amf/etc/amf.conf
        healthcheck:
            test: /bin/bash -c "/openair-amf/bin/amf-healthcheck.sh"
            interval: 10s
            timeout: 15s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.132
```

./amf.conf - This file you have to create and copy the sample config I shared (modify it as required).

N.B - I have not tested this using docker-compose so you might need to update.

**Comment by auandrew** [comment]
FYI: In my case which encounters SQN issues, I'm using UERANSIM v3.1.9 and docker-compose.

**Comment by tian008123** [comment]
@infinitydon 
Thanks for your advice!
I tried exactly what u wrote in the comment. But there is '**unhealthy**' problem with amf, sothat the core networt can not be started.

> mysql : "healthy", oai-amf : "unhealthy", oai-smf : "healthy", oai-spgwu : "healthy"


Then I tried to enter the amf container to modify amf.conf and to perfom the command  /openair-amf/bin/oai_amf -c /openair-amf/etc/amf.conf -o. But another issure for this way is

> what(): Address already in use

**Comment by infinitydon** [comment]
@tian008123 - I suggest you check your docker-compose very well, I only gave that as a guide, I did not test with docker-compose.

Did you check the logs of the AMF container?

Why are you modifying the AMF config when the container has already started? You should not be doing since you are mapping the volume already. I hope you adapted the config I shared to your environment?

**Comment by infinitydon** [comment]
@tian008123  - I took the liberty to try the setup in docker-compose, you can check the repo below for the implementation:

https://bitbucket.org/infinitydon/oai-5g-docker-compose/src/main/

I have tested this and seems to work, let me know if you run into any issues.

N.B - You need to exec into the ueransim container manually to start the gnb and ue.

**Comment by brunodzogovic** [comment]
Hi, 
I'm following up on this issue. Seems like UERANSIM uses the IA0 algorithm for emergency connectivity only. OAI 5G core does not do that and indicates that the NIA0 is the first to be used algorithm for integrity check manually. I have two deployments of core networks, one with compose and one with Kubernetes, the issue is the same when it comes to UERANSIM. Normal UEs can connect through gNBs driven by USRPs or rfsimulators to both networks, but only UERANSIM has this issue so far. If only there was an option to skip the usage of IA0 in UERANSIM and go with IA1 for example, but haven't found solution so far. 

```
UERANSIM v3.2.6
[2022-02-01 12:01:19.801] [sctp] [info] Trying to establish SCTP connection... (192.168.10.105:38412)
[2022-02-01 12:01:19.803] [sctp] [info] SCTP connection established (192.168.10.105:38412)
[2022-02-01 12:01:19.803] [sctp] [debug] SCTP association setup ascId[50]
[2022-02-01 12:01:19.803] [ngap] [debug] Sending NG Setup Request
[2022-02-01 12:01:19.805] [ngap] [debug] NG Setup Response received
[2022-02-01 12:01:19.805] [ngap] [info] NG Setup procedure is successful
Running ue
UERANSIM v3.2.6
[2022-02-01 12:01:20.796] [nas] [info] UE switches to state [MM-DEREGISTERED/PLMN-SEARCH]
[2022-02-01 12:01:20.796] [rrc] [debug] UE[1] new signal detected
[2022-02-01 12:01:20.796] [rrc] [debug] New signal detected for cell[1], total [1] cells in coverage
[2022-02-01 12:01:20.796] [nas] [info] Selected plmn[208/93]
[2022-02-01 12:01:20.796] [rrc] [info] Selected cell plmn[208/93] tac[40960] category[SUITABLE]
[2022-02-01 12:01:20.796] [nas] [info] UE switches to state [MM-DEREGISTERED/PS]
[2022-02-01 12:01:20.796] [nas] [info] UE switches to state [MM-DEREGISTERED/NORMAL-SERVICE]
[2022-02-01 12:01:20.796] [nas] [debug] Initial registration required due to [MM-DEREG-NORMAL-SERVICE]
[2022-02-01 12:01:20.796] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2022-02-01 12:01:20.796] [nas] [debug] Sending Initial Registration
[2022-02-01 12:01:20.796] [nas] [info] UE switches to state [MM-REGISTER-INITIATED]
[2022-02-01 12:01:20.796] [rrc] [debug] Sending RRC Setup Request
[2022-02-01 12:01:20.796] [rrc] [info] RRC Setup for UE[1]
[2022-02-01 12:01:20.796] [rrc] [info] RRC connection established
[2022-02-01 12:01:20.796] [rrc] [info] UE switches to state [RRC-CONNECTED]
[2022-02-01 12:01:20.796] [nas] [info] UE switches to state [CM-CONNECTED]
[2022-02-01 12:01:20.796] [ngap] [debug] Initial NAS message received from UE[1]
[2022-02-01 12:01:20.839] [nas] [debug] Authentication Request received
[2022-02-01 12:01:20.889] [nas] [debug] Security Mode Command received
[2022-02-01 12:01:20.889] [nas] [error] [IA0] cannot be accepted as the UE does not have an emergency
[2022-02-01 12:01:20.889] [nas] [error] Rejecting Security Mode Command with cause [SEC_MODE_REJECTED_UNSPECIFIED]
[2022-02-01 12:01:35.811] [nas] [debug] NAS timer[3510] expired [1]
[2022-02-01 12:01:35.811] [nas] [info] UE switches to state [MM-DEREGISTERED/PS]
[2022-02-01 12:01:35.811] [nas] [info] UE switches to state [5U2-NOT-UPDATED]
[2022-02-01 12:01:35.811] [nas] [info] Performing local release of NAS connection
[2022-02-01 12:01:35.811] [nas] [info] UE switches to state [MM-DEREGISTERED/ATTEMPTING-REGISTRATION]
[2022-02-01 12:01:35.811] [rrc] [info] UE switches to state [RRC-IDLE]
[2022-02-01 12:01:35.811] [nas] [info] UE switches to state [CM-IDLE]
[2022-02-01 12:01:36.008] [rrc] [debug] UE[2] new signal detected
[2022-02-01 12:01:37.009] [rls] [debug] UE[1] signal lost
[2022-02-01 12:01:45.821] [nas] [debug] NAS timer[3511] expired [1]
[2022-02-01 12:01:45.821] [nas] [debug] Initial registration required due to [T3511-EXPIRY-IN-ATT-REG]
[2022-02-01 12:01:45.821] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2022-02-01 12:01:45.821] [nas] [debug] Sending Initial Registration
[2022-02-01 12:01:45.821] [nas] [debug] Deleting NAS security context
[2022-02-01 12:01:45.821] [rrc] [debug] Sending RRC Setup Request
[2022-02-01 12:01:45.821] [nas] [info] UE switches to state [MM-REGISTER-INITIATED]
[2022-02-01 12:01:45.821] [rrc] [info] RRC Setup for UE[2]
[2022-02-01 12:01:45.821] [rrc] [info] RRC connection established
[2022-02-01 12:01:45.821] [rrc] [info] UE switches to state [RRC-CONNECTED]
[2022-02-01 12:01:45.821] [nas] [info] UE switches to state [CM-CONNECTED]
[2022-02-01 12:01:45.821] [ngap] [debug] Initial NAS message received from UE[2]
[2022-02-01 12:01:45.866] [nas] [debug] Authentication Request received
[2022-02-01 12:01:45.897] [nas] [debug] Security Mode Command received
[2022-02-01 12:01:45.897] [nas] [error] [IA0] cannot be accepted as the UE does not have an emergency
[2022-02-01 12:01:45.897] [nas] [error] Rejecting Security Mode Command with cause [SEC_MODE_REJECTED_UNSPECIFIED]
[2022-02-01 12:02:00.836] [nas] [debug] NAS timer[3510] expired [1]
[2022-02-01 12:02:00.836] [nas] [info] UE switches to state [MM-DEREGISTERED/PS]
[2022-02-01 12:02:00.836] [nas] [info] Performing local release of NAS connection
[2022-02-01 12:02:00.836] [nas] [info] UE switches to state [MM-DEREGISTERED/ATTEMPTING-REGISTRATION]
[2022-02-01 12:02:00.836] [rrc] [info] UE switches to state [RRC-IDLE]
[2022-02-01 12:02:00.836] [nas] [info] UE switches to state [CM-IDLE]
```

**Comment by aligungr** [comment]
@brunodzogovic 

I intentionally disabled the IA0 in UE normal registration, because of the following passage:

From 24.501 5.4.2.3
`The UE shall accept a SECURITY MODE COMMAND message indicating the "null integrity protection algorithm"
5G-EA0 as the selected 5G NAS integrity algorithm only if the message is received when the UE is registered for
emergency services, performing initial registration for emergency services or establishing an emergency PDU session.`

So, our UE does not allow IA0 for normal registration, but only emergency registration.

--

However you can actually set the integrity algorithm to any other value in OAI configurations. In this way you can solve this.

BR

**Comment by shariquemohammad** [comment]
Hello All 

During 5G SA Configuration, I am not able to ping 5G Core container AMF 192. 168.70.132 it is on VM Workstation 16.0 . I am trying from RAN from Host (Ubuntu 18.04)

I am using SDR B210 and Samsung Ue that supports 5G SA

**5GC –Below snap shot (5G SA VM Workstation)** 
![image](https://user-images.githubusercontent.com/63775531/170975580-778f63eb-0f46-4874-8a02-5e6f00bbfd64.png)


**5G RAN –Below snap shot (SDR USRP B210)**
![image](https://user-images.githubusercontent.com/63775531/170975708-d47ee541-0471-4505-9a3e-2e29d37e9cae.png)


**Problem : I am unable to ping the AMF Container from RAN Host**
![image](https://user-images.githubusercontent.com/63775531/170975788-64bbf033-c130-41cd-b082-6a7381269bac.png)

The DEOM-OAI bridge is added and i can ping from RAN
I can also ping RAN from VM 

I am not able to ping AMF so NGAP protocol is not dispalyed in wiresshark

Attached is all teh logs and wireshark

any help is appreciated

Thanks 
sharique 

[https://mega.nz/folder/JWlnkTxR#E_Npn7Bz3zDMxkCYz-czvw](url)

**Comment by Gyrusk** [comment]
> [@tian008123](https://github.com/tian008123) - I took the liberty to try the setup in docker-compose, you can check the repo below for the implementation:
> 
> https://bitbucket.org/infinitydon/oai-5g-docker-compose/src/main/
> 
> I have tested this and seems to work, let me know if you run into any issues.
> 
> N.B - You need to exec into the ueransim container manually to start the gnb and ue.

Is there any implementation on how to set up OAI on two different machines without the use of a USRP. One machine running the rf simulator and the other running the core. Can anyone help us with all the config files we are supposed to change, suppose we are using UERANSIM?
